BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Expenses" (
	"Quantity"	INTEGER,
	"Description"	TEXT,
	"Group"	TEXT,
	"Date"	TEXT
);
CREATE TABLE IF NOT EXISTS "PaidBy" (
	"User1"	INTEGER,
	"User2"	INTEGER
);
CREATE TABLE IF NOT EXISTS "Groups" (
	"Group"	INTEGER,
	"User2"	INTEGER
);
COMMIT;